=begin
#Metronome API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: info@privatedataservices.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Metronome::AgingStrategy
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Metronome::AgingStrategy do
  let(:instance) { Metronome::AgingStrategy.new }

  describe 'test an instance of AgingStrategy' do
    it 'should create an instance of AgingStrategy' do
      expect(instance).to be_instance_of(Metronome::AgingStrategy)
    end
  end
end
