=begin
#Metronome API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: info@privatedataservices.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Metronome::PermissionDeniedResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Metronome::PermissionDeniedResponse do
  let(:instance) { Metronome::PermissionDeniedResponse.new }

  describe 'test an instance of PermissionDeniedResponse' do
    it 'should create an instance of PermissionDeniedResponse' do
      expect(instance).to be_instance_of(Metronome::PermissionDeniedResponse)
    end
  end
  describe 'test attribute "error_code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["unknown-customer", "account-restricted", "api-key-lacks-permission"])
      # validator.allowable_values.each do |value|
      #   expect { instance.error_code = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "customer_status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["read-write", "read-only", "disabled"])
      # validator.allowable_values.each do |value|
      #   expect { instance.customer_status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "api_key_status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["enabled", "disabled"])
      # validator.allowable_values.each do |value|
      #   expect { instance.api_key_status = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "granted_permissions"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "required_permission"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "internal_contact"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
