# -*- encoding: utf-8 -*-

=begin
#Metronome API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: info@privatedataservices.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "metronome/version"

Gem::Specification.new do |s|
  s.name        = "pds-metronome"
  s.version     = Metronome::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Private Data Services"]
  s.email       = ["info@privatedataservices.com"]
  s.homepage    = "https://privatedataservices.com"
  s.summary     = "Track usage of your Personally Identifiable Information (PII) according to policies you define.  Expire PII with confidence once it has served its purpose."
  s.description = "Define Metronome policies, API keys and submit PII telemetry.  Query data expiry notices."
  s.license     = "MS-PL"
  s.required_ruby_version = ">= 2.6.0"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty?  && !f.end_with?(".gem") && !f.end_with?(".gemspec") }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
