=begin
#Metronome API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: info@privatedataservices.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

# Common files
require 'metronome/api_client'
require 'metronome/api_error'
require 'metronome/version'
require 'metronome/configuration'

# Models
require 'metronome/models/access_type'
require 'metronome/models/aging_offset_unit'
require 'metronome/models/aging_strategy'
require 'metronome/models/api_key_data'
require 'metronome/models/api_key_data_list_response'
require 'metronome/models/api_key_list_response'
require 'metronome/models/create_api_key_request'
require 'metronome/models/create_or_modify_api_key_response'
require 'metronome/models/create_or_modify_policy_request'
require 'metronome/models/create_or_modify_policy_response'
require 'metronome/models/expire_item_response'
require 'metronome/models/expire_sub_item_response'
require 'metronome/models/expiry_response'
require 'metronome/models/expiry_response_pending_inner'
require 'metronome/models/get_many_api_keys200_response'
require 'metronome/models/get_many_policies200_response'
require 'metronome/models/item_expiry'
require 'metronome/models/item_metadata_response'
require 'metronome/models/item_or_sub_item_access_log'
require 'metronome/models/item_or_sub_item_policy_response'
require 'metronome/models/modify_api_key_request'
require 'metronome/models/permission'
require 'metronome/models/permission_denied_response'
require 'metronome/models/policy_data'
require 'metronome/models/policy_data_list_response'
require 'metronome/models/policy_list_response'
require 'metronome/models/put_api_key_request'
require 'metronome/models/signup_request'
require 'metronome/models/signup_response'
require 'metronome/models/sub_item_metadata_response'
require 'metronome/models/sub_items_expiry'
require 'metronome/models/telemetry_observation'
require 'metronome/models/telemetry_request'
require 'metronome/models/validation_error_response_inner'
require 'metronome/models/validation_problem'

# APIs
require 'metronome/api/access_management_api'
require 'metronome/api/data_expiry_api'
require 'metronome/api/item_access_api'
require 'metronome/api/policy_management_api'
require 'metronome/api/telemetry_api'

module Metronome
  class << self
    # Customize default settings for the SDK using block.
    #   Metronome.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
        Configuration.default.check_required_attributes  # PDS patch
      else
        Configuration.default
      end
    end
  end
end
