=begin
#Metronome API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: info@privatedataservices.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'date'
require 'time'

module Metronome
  class Permission
    API_KEY_WRITE = "api-key-write".freeze
    API_KEY_READ = "api-key-read".freeze
    POLICY_READ = "policy-read".freeze
    POLICY_WRITE = "policy-write".freeze
    ITEM_READ = "item-read".freeze
    TELEMETRY_WRITE = "telemetry-write".freeze
    EXPIRY_NOTICE_READ = "expiry-notice-read".freeze

    def self.all_vars
      @all_vars ||= [API_KEY_WRITE, API_KEY_READ, POLICY_READ, POLICY_WRITE, ITEM_READ, TELEMETRY_WRITE, EXPIRY_NOTICE_READ].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if Permission.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #Permission"
    end
  end
end
