/**
 * Metronome API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@privatedataservices.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiKeyData } from '../models/ApiKeyData';
import { HttpFile } from '../http/http';

export class ApiKeyDataListResponse {
    /**
    * Always the value \"ApiKeyDataListResponse\"
    */
    'responseType': string;
    'result': Array<ApiKeyData>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "responseType",
            "baseName": "response-type",
            "type": "string",
            "format": ""
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "Array<ApiKeyData>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApiKeyDataListResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

