/**
 * Metronome API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@privatedataservices.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExpiryResponsePendingInner } from '../models/ExpiryResponsePendingInner';
import { HttpFile } from '../http/http';

export class ExpiryResponse {
    /**
    * Date in YYYYMMDD format.
    */
    'expiryDate'?: string;
    'pending': Array<ExpiryResponsePendingInner>;
    'complete': Array<ExpiryResponsePendingInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "expiryDate",
            "baseName": "expiry-date",
            "type": "string",
            "format": "date"
        },
        {
            "name": "pending",
            "baseName": "pending",
            "type": "Array<ExpiryResponsePendingInner>",
            "format": ""
        },
        {
            "name": "complete",
            "baseName": "complete",
            "type": "Array<ExpiryResponsePendingInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExpiryResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

