/**
 * Metronome API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@privatedataservices.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ItemExpiry } from '../models/ItemExpiry';
import { SubItemsExpiry } from '../models/SubItemsExpiry';
import { HttpFile } from '../http/http';

export class ExpiryResponsePendingInner {
    /**
    * Always the value \"SubItemsExpiry\"
    */
    'expiryType': string;
    'itemId': string;
    'parentItemId': string;
    'subItems': Array<string>;

    static readonly discriminator: string | undefined = "expiryType";

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "expiryType",
            "baseName": "expiry-type",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemId",
            "baseName": "item-id",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentItemId",
            "baseName": "parent-item-id",
            "type": "string",
            "format": ""
        },
        {
            "name": "subItems",
            "baseName": "sub-items",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ExpiryResponsePendingInner.attributeTypeMap;
    }

    public constructor() {
        this.expiryType = "ExpiryResponsePendingInner";
    }
}

