/**
 * Metronome API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@privatedataservices.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PolicyData } from '../models/PolicyData';
import { PolicyDataListResponse } from '../models/PolicyDataListResponse';
import { PolicyListResponse } from '../models/PolicyListResponse';
import { HttpFile } from '../http/http';

export class GetManyPolicies200Response {
    /**
    * Always the value \"PolicyDataListResponse\"
    */
    'responseType': string;
    /**
    * The number of policies with the given prefix.  Count of all policies if no prefix was given.
    */
    'count': number;
    /**
    * How many items were skipped, specified in the request.
    */
    'offset'?: number;
    /**
    * The maximum number of items to return, specified in the request.
    */
    'limit'?: number;
    /**
    * The string prefix to limit policy names, specified in the request.
    */
    'prefix'?: string;
    'result': Array<PolicyData> | Array<string>;  // PDS: Added union type to work around generator bug

    static readonly discriminator: string | undefined = "responseType";

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "responseType",
            "baseName": "response-type",
            "type": "string",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "prefix",
            "baseName": "prefix",
            "type": "string",
            "format": ""
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "Array<PolicyData>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GetManyPolicies200Response.attributeTypeMap;
    }

    public constructor() {
        this.responseType = "GetManyPolicies200Response";
    }
}

