/**
 * Metronome API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@privatedataservices.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ItemOrSubItemPolicyResponse {
    /**
    * A policy that was applied to this item or sub-item
    */
    'policyId': string;
    /**
    * The date at which this item or sub-item should expire according to this policy
    */
    'expiryDate'?: string;
    /**
    * The date at which this policy was last applied to this item or sub-item
    */
    'lastApplicationDate'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "policyId",
            "baseName": "policy-id",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiryDate",
            "baseName": "expiry-date",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastApplicationDate",
            "baseName": "last-application-date",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ItemOrSubItemPolicyResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

