/**
 * Metronome API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@privatedataservices.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccessType } from '../models/AccessType';
import { HttpFile } from '../http/http';

export class ItemOrSubItemAccessLog {
    'timestamp': Date;
    'accessType': AccessType;
    /**
    * The ID of the system that accessed the data
    */
    'accessAuthoriser': string;
    'accessPolicies': Array<string>;
    /**
    * The policy which governed data expiry after this data access
    */
    'effectiveExpiryPolicy': string;
    /**
    * The date to which this item or sub-item would be retained after this access
    */
    'effectiveExpiryDate'?: string;
    'accessedSubItems'?: Array<string>;
    /**
    * Present and true only when the item expired as a result of this access
    */
    'expired'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "accessType",
            "baseName": "access-type",
            "type": "AccessType",
            "format": ""
        },
        {
            "name": "accessAuthoriser",
            "baseName": "access-authoriser",
            "type": "string",
            "format": ""
        },
        {
            "name": "accessPolicies",
            "baseName": "access-policies",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "effectiveExpiryPolicy",
            "baseName": "effective-expiry-policy",
            "type": "string",
            "format": ""
        },
        {
            "name": "effectiveExpiryDate",
            "baseName": "effective-expiry-date",
            "type": "string",
            "format": ""
        },
        {
            "name": "accessedSubItems",
            "baseName": "accessed-sub-items",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "expired",
            "baseName": "expired",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ItemOrSubItemAccessLog.attributeTypeMap;
    }

    public constructor() {
    }
}



