/**
 * Metronome API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@privatedataservices.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Permission } from '../models/Permission';
import { HttpFile } from '../http/http';

export class PermissionDeniedResponse {
    'errorCode': PermissionDeniedResponseErrorCodeEnum;
    'customerStatus'?: PermissionDeniedResponseCustomerStatusEnum;
    'apiKeyStatus'?: PermissionDeniedResponseApiKeyStatusEnum;
    'grantedPermissions'?: Array<Permission>;
    'requiredPermission'?: Permission;
    'internalContact'?: string;
    'message'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "errorCode",
            "baseName": "error-code",
            "type": "PermissionDeniedResponseErrorCodeEnum",
            "format": ""
        },
        {
            "name": "customerStatus",
            "baseName": "customer-status",
            "type": "PermissionDeniedResponseCustomerStatusEnum",
            "format": ""
        },
        {
            "name": "apiKeyStatus",
            "baseName": "api-key-status",
            "type": "PermissionDeniedResponseApiKeyStatusEnum",
            "format": ""
        },
        {
            "name": "grantedPermissions",
            "baseName": "granted-permissions",
            "type": "Array<Permission>",
            "format": ""
        },
        {
            "name": "requiredPermission",
            "baseName": "required-permission",
            "type": "Permission",
            "format": ""
        },
        {
            "name": "internalContact",
            "baseName": "internal-contact",
            "type": "string",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PermissionDeniedResponse.attributeTypeMap;
    }

    public constructor() {
    }
}


export type PermissionDeniedResponseErrorCodeEnum = "unknown-customer" | "account-restricted" | "api-key-lacks-permission" ;
export type PermissionDeniedResponseCustomerStatusEnum = "read-write" | "read-only" | "disabled" ;
export type PermissionDeniedResponseApiKeyStatusEnum = "enabled" | "disabled" ;

