/**
 * Metronome API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@privatedataservices.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SignupResponse {
    'devApiUrl': string;
    'devMasterApiKey': string;
    'productionApiUrl': string;
    'productionMasterApiKey': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "devApiUrl",
            "baseName": "dev-api-url",
            "type": "string",
            "format": ""
        },
        {
            "name": "devMasterApiKey",
            "baseName": "dev-master-api-key",
            "type": "string",
            "format": ""
        },
        {
            "name": "productionApiUrl",
            "baseName": "production-api-url",
            "type": "string",
            "format": ""
        },
        {
            "name": "productionMasterApiKey",
            "baseName": "production-master-api-key",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SignupResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

