/**
 * Metronome API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@privatedataservices.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TelemetryObservation } from '../models/TelemetryObservation';
import { HttpFile } from '../http/http';

export class TelemetryRequest {
    /**
    * The time the observation happened in UTC timezone
    */
    'observationTime': Date;
    'policies': Array<string>;
    'observations': Array<TelemetryObservation>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "observationTime",
            "baseName": "observation-time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "policies",
            "baseName": "policies",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "observations",
            "baseName": "observations",
            "type": "Array<TelemetryObservation>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TelemetryRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

