/**
 * Metronome API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@privatedataservices.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValidationProblem } from '../models/ValidationProblem';
import { HttpFile } from '../http/http';

export class ValidationErrorResponseInner {
    'spec': string;
    'requestFromCustomer': any;
    'problems': Array<ValidationProblem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "spec",
            "baseName": "spec",
            "type": "string",
            "format": ""
        },
        {
            "name": "requestFromCustomer",
            "baseName": "request-from-customer",
            "type": "any",
            "format": ""
        },
        {
            "name": "problems",
            "baseName": "problems",
            "type": "Array<ValidationProblem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ValidationErrorResponseInner.attributeTypeMap;
    }

    public constructor() {
    }
}

