=begin
#Metronome API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: info@privatedataservices.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Metronome::AccessManagementApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccessManagementApi' do
  before do
    # run before each test
    @api_instance = Metronome::AccessManagementApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccessManagementApi' do
    it 'should create an instance of AccessManagementApi' do
      expect(@api_instance).to be_instance_of(Metronome::AccessManagementApi)
    end
  end

  # unit tests for get_api_key
  # Read a specific API key
  # @param api_key 
  # @param [Hash] opts the optional parameters
  # @return [ApiKeyData]
  describe 'get_api_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_many_api_keys
  # Read many API keys alphanumerically sorted
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :offset The number of keys to drop from the start
  # @option opts [Integer] :limit The number of keys to include
  # @option opts [Boolean] :include_data Whether to include permissions, status, description etc.
  # @return [GetManyApiKeys200Response]
  describe 'get_many_api_keys test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for put_api_key
  # Create or modify an API key
  # @param api_key The API key to be modified or &#39;create&#39; for a new key
  # @param [Hash] opts the optional parameters
  # @option opts [PutApiKeyRequest] :put_api_key_request 
  # @return [CreateOrModifyApiKeyResponse]
  describe 'put_api_key test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for sign_up
  # Open end point for signing up new customers
  # @param [Hash] opts the optional parameters
  # @option opts [SignupRequest] :signup_request 
  # @return [SignupResponse]
  describe 'sign_up test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
