=begin
#Metronome API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: info@privatedataservices.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Metronome::DataExpiryApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DataExpiryApi' do
  before do
    # run before each test
    @api_instance = Metronome::DataExpiryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DataExpiryApi' do
    it 'should create an instance of DataExpiryApi' do
      expect(@api_instance).to be_instance_of(Metronome::DataExpiryApi)
    end
  end

  # unit tests for get_expiry_notices
  # Read items and sub-items that will or have already been expired on the given date
  # @param date The date to query
  # @param [Hash] opts the optional parameters
  # @return [ExpiryResponse]
  describe 'get_expiry_notices test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
